// Generated by gencpp from file hybrid_navigation/Detection.msg
// DO NOT EDIT!


#ifndef HYBRID_NAVIGATION_MESSAGE_DETECTION_H
#define HYBRID_NAVIGATION_MESSAGE_DETECTION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hybrid_navigation
{
template <class ContainerAllocator>
struct Detection_
{
  typedef Detection_<ContainerAllocator> Type;

  Detection_()
    : class_id(0)
    , class_name()
    , confidence(0.0)
    , bbox_center_x(0.0)
    , bbox_center_y(0.0)
    , distance(0.0)
    , angle(0.0)  {
    }
  Detection_(const ContainerAllocator& _alloc)
    : class_id(0)
    , class_name(_alloc)
    , confidence(0.0)
    , bbox_center_x(0.0)
    , bbox_center_y(0.0)
    , distance(0.0)
    , angle(0.0)  {
  (void)_alloc;
    }



   typedef int32_t _class_id_type;
  _class_id_type class_id;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _class_name_type;
  _class_name_type class_name;

   typedef float _confidence_type;
  _confidence_type confidence;

   typedef float _bbox_center_x_type;
  _bbox_center_x_type bbox_center_x;

   typedef float _bbox_center_y_type;
  _bbox_center_y_type bbox_center_y;

   typedef float _distance_type;
  _distance_type distance;

   typedef float _angle_type;
  _angle_type angle;





  typedef boost::shared_ptr< ::hybrid_navigation::Detection_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hybrid_navigation::Detection_<ContainerAllocator> const> ConstPtr;

}; // struct Detection_

typedef ::hybrid_navigation::Detection_<std::allocator<void> > Detection;

typedef boost::shared_ptr< ::hybrid_navigation::Detection > DetectionPtr;
typedef boost::shared_ptr< ::hybrid_navigation::Detection const> DetectionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hybrid_navigation::Detection_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hybrid_navigation::Detection_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hybrid_navigation::Detection_<ContainerAllocator1> & lhs, const ::hybrid_navigation::Detection_<ContainerAllocator2> & rhs)
{
  return lhs.class_id == rhs.class_id &&
    lhs.class_name == rhs.class_name &&
    lhs.confidence == rhs.confidence &&
    lhs.bbox_center_x == rhs.bbox_center_x &&
    lhs.bbox_center_y == rhs.bbox_center_y &&
    lhs.distance == rhs.distance &&
    lhs.angle == rhs.angle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hybrid_navigation::Detection_<ContainerAllocator1> & lhs, const ::hybrid_navigation::Detection_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hybrid_navigation

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::hybrid_navigation::Detection_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hybrid_navigation::Detection_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hybrid_navigation::Detection_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hybrid_navigation::Detection_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hybrid_navigation::Detection_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hybrid_navigation::Detection_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hybrid_navigation::Detection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7efc4f850157fd2f62ebe2843f081934";
  }

  static const char* value(const ::hybrid_navigation::Detection_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7efc4f850157fd2fULL;
  static const uint64_t static_value2 = 0x62ebe2843f081934ULL;
};

template<class ContainerAllocator>
struct DataType< ::hybrid_navigation::Detection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hybrid_navigation/Detection";
  }

  static const char* value(const ::hybrid_navigation::Detection_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hybrid_navigation::Detection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 class_id\n"
"string class_name\n"
"float32 confidence\n"
"float32 bbox_center_x  # Nuevo campo\n"
"float32 bbox_center_y  # Nuevo campo\n"
"float32 distance       # Opcional para integración con profundidad\n"
"float32 angle         # Opcional para posición angular\n"
;
  }

  static const char* value(const ::hybrid_navigation::Detection_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hybrid_navigation::Detection_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.class_id);
      stream.next(m.class_name);
      stream.next(m.confidence);
      stream.next(m.bbox_center_x);
      stream.next(m.bbox_center_y);
      stream.next(m.distance);
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Detection_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hybrid_navigation::Detection_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hybrid_navigation::Detection_<ContainerAllocator>& v)
  {
    s << indent << "class_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.class_id);
    s << indent << "class_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.class_name);
    s << indent << "confidence: ";
    Printer<float>::stream(s, indent + "  ", v.confidence);
    s << indent << "bbox_center_x: ";
    Printer<float>::stream(s, indent + "  ", v.bbox_center_x);
    s << indent << "bbox_center_y: ";
    Printer<float>::stream(s, indent + "  ", v.bbox_center_y);
    s << indent << "distance: ";
    Printer<float>::stream(s, indent + "  ", v.distance);
    s << indent << "angle: ";
    Printer<float>::stream(s, indent + "  ", v.angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HYBRID_NAVIGATION_MESSAGE_DETECTION_H
